# vim: set filetype=yaml expandtab tabstop=2 shiftwidth=2 softtabstop=2 background=dark :

#- name: import pg95 repo
#  yum:
#    name: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-3.noarch.rpm
#    state: installed
#
#- name: install pg95
#  yum:
#    name: postgresql95-server, postgresql95-contrib, python-psycopg2
#    state: installed
#
#- name: init DB dir on master
#  shell: "{{ postgres_ha_pg_bindir }}/postgresql95-setup initdb"
#  args:
#    creates: "{{ postgres_ha_pg_data }}/PG_VERSION"
#  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node
#
#- name: create DB conf dir
#  file: state=directory path="{{ postgres_ha_pg_data }}/conf.d"
#  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node
#  args:
#    owner: postgres
#    group: postgres
#    mode:  0700
#
#- name: push DB config (clustering)
#  template: src=postgresql.conf.j2 dest="{{ postgres_ha_pg_data }}/postgresql.conf"
#  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node
#  args:
#    owner: postgres
#    group: postgres
#    mode:  0600

- name: alter clustering-related settings in postgresql.conf
  replace: 
    dest="{{ postgres_ha_pg_data }}/postgresql.conf
    regexp="^([# ]*{{ item.name }} *=.*$)"
    replace="{{ item.name }} = {{ item.value }}"
  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on master node
  with_dict: "{{ postgres_ha_postgresql_conf_vars }}"
  notify: restart postgresql

- meta: flush_handlers

- name: push DB config (ACL)
  template: src=pg_hba.conf.j2 dest="{{ postgres_ha_pg_data }}/pg_hba.conf"
  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node
  notify: reload postgresql
  args:
    owner: postgres
    group: postgres
    mode:  0600

- meta: flush_handlers

#hostname:port:database:username:password
- name: setup DB cluster auth (master IP)
  lineinfile: dest="~postgres/.pgpass" line="{{ postgres_ha_cluster_vip }}:{{ postgres_ha_pg_port }}:replication:postgres:{{ postgres_ha_pg_repl_pass }}" state=present
  args:
    owner: postgres
    group: postgres
    mode:  0600
    create: yes

- name: setup DB cluster replication auth (master IP)
  lineinfile: dest="~postgres/.pgpass" line="{{ postgres_ha_cluster_vip }}:{{ postgres_ha_pg_port }}:replication:{{ postgres_ha_pg_repl_user }}:{{ postgres_ha_pg_repl_pass }}" state=present
  args:
    owner: postgres
    group: postgres
    mode:  0600
    create: yes

- name: setup DB cluster replication auth (all nodes)
  lineinfile: dest="~postgres/.pgpass" line="{{ hostvars[item].ansible_default_ipv4.address }}:{{ postgres_ha_pg_port }}:replication:{{ postgres_ha_pg_repl_user }}:{{ postgres_ha_pg_repl_pass }}" state=present
  with_items: "{{play_hosts}}"
  args:
    owner: postgres
    group: postgres
    mode:  0600
    create: yes

- name: check if master host ("{{ postgres_ha_cluster_master_host }}") is really a DB master
  shell: psql -Aqtc "SELECT pg_is_in_recovery()"
  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: no
  register: is_slave
  failed_when: is_slave.stdout == 't'

- name: mark master DB
  lineinfile: dest="{{ postgres_ha_pg_data }}/.synchronized" line="DO NOT REMOVE THIS FILE! Otherwise DB sync can go wrong." state=present
  args:
    owner: postgres
    group: postgres
    mode:  0600
    create: yes
  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node
  register: create_syncfile

- name: check if DB is running (failure is ok)
  #shell: /bin/sh -c 'if {{ postgres_ha_pg_bindir }}/pg_ctl -D "{{ postgres_ha_pg_data }}" status &> /dev/null; then echo True; else echo False; fi'
  shell: "{{ postgres_ha_pg_bindir }}/pg_ctl -D {{ postgres_ha_pg_data }} status"
  register: db_running
  become: yes
  become_user: postgres
  ignore_errors: True

# check if the DB is already clustered
# If the resource constraint already exists, it means that DB clustering was fully applied before
# and the database should run only from cluster resource.
- name: check if DB is running under cluster (failure is OK)
  #shell: /bin/sh -c 'if pcs resource show "{{ postgres_ha_cluster_pg_HA_res_name }}" &> /dev/null; then echo True; else echo False; fi'
  #shell: pcs resource show "{{ postgres_ha_cluster_pg_HA_res_name }}"
  shell: pcs constraint location show resources "{{ postgres_ha_cluster_pg_HA_res_name }}" | grep -q Enabled
  register: db_resource_exists
  ignore_errors: True

- name: start master DB if necessary (without cluster)
  service: name="{{ postgres_ha_pg_systemd_svcname }}" state=started enabled=yes
  when: (inventory_hostname == "{{ postgres_ha_cluster_master_host }}") and
        (db_resource_exists|failed) and
        (db_running|failed)

# if DB is clustered and is not running, we have a problem.. try at least cleaning the resource status
- name: start master DB if necessary (in cluster)
  shell: pcs resource cleanup "{{ postgres_ha_cluster_pg_HA_res_name }}" && sleep 15
  when: (inventory_hostname == "{{ postgres_ha_cluster_master_host }}") and
        (db_resource_exists|succeeded) and
        (db_running|failed)

#- name: create test db
#  postgresql_db: name=testDB
#  port: "{{ postgres_ha_pg_port }}"
#  become: yes
#  become_user: postgres
#  vars:
#    ansible_ssh_pipelining: no
#  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node

- name: setup DB replication auth
  postgresql_user:
    name: "{{ postgres_ha_pg_repl_user }}"
    state: present
    port: "{{ postgres_ha_pg_port }}"
    password: "{{ postgres_ha_pg_repl_pass }}"
    role_attr_flags: SUPERUSER,LOGIN
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: no
  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node

#- name: re-check DB datadir
#  find: paths="{{ postgres_ha_pg_data }}"
#  register: datadir_files

# if the file does not exist, DB sync is needed
- name: check if DB sync is required
  stat: path="{{ postgres_ha_pg_data }}/.synchronized"
  register: db_sync_file

- name: stop slave DB
  service: name="{{ postgres_ha_pg_systemd_svcname }}" state=stopped enabled=false
  when: (not db_sync_file.stat.exists) and
        (db_resource_exists|failed) and
        (db_running|succeeded)

- name: remove slave DB datadir before sync
  file: state=absent path="{{ postgres_ha_pg_data }}"
  #shell: rm -rf "{{ postgres_ha_pg_data }}" 
  #args:
  #  creates: "{{ postgres_ha_pg_data }}/.synchronized"     # will not delete if the file exists (means that DB is already synced)
  when: not db_sync_file.stat.exists
  register: delete_datadir

# replicate slave node (assumes firewall is already setup)
# run only on slave nodes and only when postgres datadir is empty
- name: synchronize slave databases
  shell: '{{ postgres_ha_pg_bindir }}/pg_basebackup -h "{{ hostvars[postgres_ha_cluster_master_host].ansible_default_ipv4.address }}" -p {{ postgres_ha_pg_port }} -R -D "{{ postgres_ha_pg_data }}" -U "{{ postgres_ha_pg_repl_user }}" -v -P --xlog-method=stream'
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: no
  when: delete_datadir.changed
  #when: (inventory_hostname != "{{ postgres_ha_cluster_master_host }}") and
  #      (datadir_files.matched|int == 0)

#- name: Exterminate mankind
#  pause: prompt='Please confirm you want to exterminate mankind! Press return to continue. Press Ctrl+c and then "a" to abort'

- name: start slave DBs
  service: name="{{ postgres_ha_pg_systemd_svcname }}" state=started enabled=yes
  when: (inventory_hostname != "{{ postgres_ha_cluster_master_host }}") and
        (db_resource_exists|failed) and
        delete_datadir.changed

- name: check if slaves are connected
  shell: psql -Aqtc "SELECT count(*) FROM pg_stat_replication"
  when: inventory_hostname == "{{ postgres_ha_cluster_master_host }}"   # run only on one node
  become: yes
  become_user: postgres
  register: slavecount
  vars:
    ansible_ssh_pipelining: no
  until: (slavecount.stdout|string) == ((play_hosts|length - 1)|string)
  retries: 10
  delay: 2
