---
- debug: msg='MASTER NODE SET TO {{ postgres_ha_cluster_master_host }}'
  run_once: true

- name: verify postgres_ha_cluster_master_host
  fail:
    msg: "CRITICAL: defined master host ({{ postgres_ha_cluster_master_host }}) is not in host list ({{ ansible_play_batch }})"
  when: postgres_ha_cluster_master_host not in ansible_play_batch

- name: identify the OS
  set_fact:
    os_version: 'centos{{ ansible_distribution_major_version }}'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
