---
- debug: msg='MASTER NODE SET TO {{ postgres_ha_cluster_master_host }}'
  run_once: true

- name: verify postgres_ha_cluster_master_host
  fail:
    msg: "CRITICAL: defined master host ({{ postgres_ha_cluster_master_host }}) is not in host list ({{ ansible_play_batch }})"
  when: postgres_ha_cluster_master_host not in ansible_play_batch

